#제목1
##재목2
###제목3

In [9]:
import numpy as np

data = [0,1,2,3,4,5]
a1 = np.array(data) # 리스트를 넘파이 배열로 생성

print(a1)
print( type(a1) )

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
data2 = [0,1,2,3,0.5,3.14]
a2 = np.array(data2)
# 정수와 실수가 섞여 있으면 전부 실수로 변환
print( a2 )

[0.   1.   2.   3.   0.5  3.14]


In [11]:
x = np.array([0.1,0.2,0.3])
print(x.shape) # 배열 구조
print(x.dtype) # 배열 요소들의 타입

(3,)
float64


In [12]:
y = np.array( ([1,2,3],[4,5,6]) )
print(y.shape) # 배열 구조
print(y.dtype)

(2, 3)
int64


In [14]:
a3 = np.arange(1,10)
print(a3)
print(  type(a3) )

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [15]:
a4 = np.arange(1,10,2)
print(a4)

[1 3 5 7 9]


In [18]:
a5 = np.arange(12).reshape(4,3)

print(a5)
print( a5.shape )

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [19]:
# 개수 지정해서 배열 만들기
a6 = np.linspace(1,10,5)
print(a6)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
a7 = np.linspace(0, np.pi, 20) # 0부터 3.14까지 20개 만들기
print(a7)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [ ]:
a8 = np.zeros(10) # 0으로 10칸 채워라
print(a8)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
a9 = np.zeros((3,4)) # 2차원 배열 생성(4칸짜리 3묶음)
print(a9)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
a10 = np.ones(5) # 1로 5칸 만들어라
print(a10)

[1. 1. 1. 1. 1.]


In [ ]:
a11 = np.ones((3,2)) 
print(a11)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a12 = np.eye(5) #5*5짜리 배열이 생성되고 대각선으로 1이 만들어짐
print(a12)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a13 = np.array(['1.5','3.14','3']) # 문자열 생성
print(a13)
print(a13.dtype) #<U4 는 U -> 유니코드/4->최대4개

['1.5' '3.14' '3']
<U4


In [ ]:
num_a13 = a13.astype(float) # 자료형 바꿈
print(num_a13)
print(num_a13.dtype)

[1.5  3.14 3.  ]
float64


In [ ]:
a14 = np.array(['1','2','3','4']) 
int_a14 = a14.astype(int) # a13으로 하면 정수만 들어있는게 아니고 실수도 포함되어 있어서 오류뜨는게 정상임
print(int_a14)

[1 2 3 4]


In [ ]:
a15 = np.random.rand(2,3) # 난수 생성 (기본적으로 난수는 0~1미만, 즉 0.9999까지 생성)
print(a15)

[[0.34861499 0.70666357 0.24368707]
 [0.97691029 0.09322839 0.81203842]]


In [39]:
a16 = np.random.rand(2,3,4)
print(a16)

[[[0.06531974 0.01868778 0.54071779 0.48724328]
  [0.19111327 0.26594151 0.20391399 0.17901243]
  [0.75699033 0.0933838  0.32331114 0.69229432]]

 [[0.90075203 0.46221443 0.75855972 0.99899715]
  [0.87984527 0.17809566 0.94604027 0.38875538]
  [0.04019831 0.59791076 0.08083673 0.55941839]]]


In [41]:
a17 = np.random.randint(10, size=(3,4))
print(a17)

[[8 3 5 8]
 [8 4 1 4]
 [1 8 3 4]]


In [42]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = list1 + list2
print(list3)

[1, 2, 3, 4, 5, 6]


In [48]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
print(result)

[5 7 9]


In [49]:
result = arr1*arr2
print(result)

[ 4 10 18]


In [ ]:
result = list1 * 3 # 이건 문자열처럼 뒤에 붙어서 나옴
print(result)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
result = arr1 *3 
print(result)

[3 6 9]


In [ ]:
result = (arr1 >= 2) # 논리 연산도 가능 
print(arr1)
print(result)

[1 2 3]
[False  True  True]


In [54]:
sum( list1 )
print(list1)

[1, 2, 3]


In [56]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [57]:
print(arr.sum()) # 합계
print(arr.min()) # 최소
print(arr.max()) # 최대
print(arr.mean()) # 평균
print(arr.std()) # 표준편차
print(arr.var()) # 분산

10
0
4
2.0
1.4142135623730951
2.0


In [59]:
# 인덱싱
arr = np.array([10,20,30,40,50])
print(arr[2])
print(arr[-1])

30
50


In [61]:
print( arr[1:3] )
print(arr[:2])
print(arr[3:])

[20 30]
[10 20]
[40 50]


In [65]:
# 행렬 연산
m1 = np.array([[1,2],[4,5]])
m2 = np.array([[5,6],[7,8]])
result = m1+m2
print(result)

# 행렬 합
result = np.add(m1,m2)
print(result)

[[ 6  8]
 [11 13]]
[[ 6  8]
 [11 13]]


In [ ]:
result = np.subtract(m1,m2) # 빼기
print(result)

[[-4 -4]
 [-3 -3]]


In [ ]:
result = np.multiply(m1,m2) # 더하기이긴한데 자세히 한번 더 봐야 됨
print(result)

[[ 5 12]
 [28 40]]


In [ ]:
result = np.dot(m1,m2) # 행렬 곱하기?
print(result)

[[19 22]
 [55 64]]


In [ ]:
arr = np.array([9,5,7,1,3])

print(np.sort(arr)) # 정렬
print(np.argsort(arr)) #정렬 한 값의 인덱스

print(np.argmin(arr)) # 최소값의 인덱스 
print(np.argmax(arr)) # 최대값의 인덱스

[1 3 5 7 9]
[3 4 1 2 0]
3
0


In [ ]:
# 브로드캐스팅
# 배열 간 크기가 다른 경우에도 연산을 해주는 기능
# 각 배열의 shape를 비교
# 뒤에서 차원 비교를 수행 -> 차원이 같거나 하나가 1이면 호환
a = np.array([1,2,3]) # 1차원
b = np.array([[4],[5],[6]]) # 2차원

# 연산 한번 더 봐야 할 듯
print(a.shape)
print(b.shape) 

c = a+b
print(c)
print(c.shape)

(3,)
(3, 1)
[[5 6 7]
 [6 7 8]
 [7 8 9]]
(3, 3)


2.5
