In [1]:
# Series : 라벨이 있는 1차원 데이터
import pandas as pd

# 시리즈에는 시퀀스 데이터가 들어감
# 리스트, 튜플 가능한데 보통 리스트를 많이 사용함
s1 = pd.Series([10,20,30,40,50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
print(s1.index) # 인덱스 목록

RangeIndex(start=0, stop=5, step=1)


In [ ]:
print(s1.values) # 값 목록

[10 20 30 40 50]


In [ ]:
s2 = pd.Series(['a',1,'b',3.14,123]) # 다양한 자료형 가능
print(s2)

0       a
1       1
2       b
3    3.14
4     123
dtype: object


In [8]:
import numpy as np
s3 = pd.Series([10,np.nan,30])
print(s3)

0    10.0
1     NaN
2    30.0
dtype: float64


In [ ]:
index = ['2025-09-13','2025-09-15','2025-10-20'] # 이 리스트를 인덱스로 사용함
s4 = pd.Series([100,200,300], index=index)
print(s4)

2025-09-13    100
2025-09-15    200
2025-10-20    300
dtype: int64


In [ ]:
s5 = pd.Series({'국어':100,'영어':90,'수학':50}) 
print(s5) # 딕셔너리로 만들면 키는 인덱스로, 벨류는 값(?)으로 만들어짐

국어    100
영어     90
수학     50
dtype: int64


In [16]:
# 데이터 프레임(2차원)
# 인덱스, 열, 값
index = ['하나','둘','셋']
columns = ['A','B','C']
values = [[1,2,3],[4,5,6],[7,8,9]]

df = pd.DataFrame(values, index=index, columns=columns)
print(df)

    A  B  C
하나  1  2  3
둘   4  5  6
셋   7  8  9


In [20]:
print(df.index) # 인덱스 목록
print(df.columns) # 컬럼 목록
print(df.values) # 값 목록

Index(['하나', '둘', '셋'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
data = {
  '학번':['1000','1001','1002'],
  '이름':['홍길동','고길동','유재석'],
  '점수':[80,90,50]
}
df = pd.DataFrame(data)
print(df)

     학번   이름  점수
0  1000  홍길동  80
1  1001  고길동  90
2  1002  유재석  50


In [23]:
print(df.dtypes)

학번    object
이름    object
점수     int64
dtype: object


In [ ]:
print(df.T) # 행,렬 봐꿔줌(원본이 봐뀌는 건 아님)

       0     1     2
학번  1000  1001  1002
이름   홍길동   고길동   유재석
점수    80    90    50


In [26]:
df.index = ['A','B','C']
df

학번   이름  점수
A  1000  홍길동  80
B  1001  고길동  90
C  1002  유재석  50

In [ ]:
df['이름'] # 원하는 컬럼명을 이용해서 가져올 수 있음
print(df['이름']) # 데이터 프레임이 아니라 시리즈임
print(type(df['이름']))

A    홍길동
B    고길동
C    유재석
Name: 이름, dtype: object
<class 'pandas.core.series.Series'>


In [31]:
df[['이름','점수']] # 여러개를 꺼내 올 때에는 리스트 형태로 만들어야 됨
print(type(df[['이름','점수']]))

<class 'pandas.core.frame.DataFrame'>


In [35]:
df.rename(columns={'이름':'name'}) # 컬럼명만 바꿀수도 있음(그렇다고 원본이 봐뀌진 않음)

학번 name  점수
A  1000  홍길동  80
B  1001  고길동  90
C  1002  유재석  50

In [38]:
# 워너본에 반영시키고 싶으면 대입 연산자를 사용하거나 inplace=True를 사용하면 반영 됨
df.rename(columns={'이름':'name'}, inplace=True)
df

학번 name  점수
A  1000  홍길동  80
B  1001  고길동  90
C  1002  유재석  50

In [39]:
df.head() # 데이터 목록 중에서 앞부분 n개 보기 (기본값은 5)

학번 name  점수
A  1000  홍길동  80
B  1001  고길동  90
C  1002  유재석  50

In [ ]:
df.head(1) # 제일 앞에꺼 볼 수 있음 (인덱스마냥 0부터 시작이 아니라 1부터 시작)

학번 name  점수
A  1000  홍길동  80

In [ ]:
df.tail(2) # 마지막(뒤에서부터)꺼 2개 보기는 tail

학번 name  점수
B  1001  고길동  90
C  1002  유재석  50